name: hotel_booking_app
description: "Cross-platform hotel booking application built with Flutter, BLoC, Clean Architecture and GraphQL."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  provider: ^6.1.2
  graphql_flutter: ^5.2.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
